export const SukukManagerAbi = [
  {
    inputs: [
      { internalType: "address", name: "yieldVault_", type: "address" },
      { internalType: "address", name: "initialOwner_", type: "address" },
      { internalType: "address", name: "factory_", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "SukukManager__ArrayLengthMismatch", type: "error" },
  { inputs: [], name: "SukukManager__ExceedsMaxSupply", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "actual", type: "uint256" },
    ],
    name: "SukukManager__HoldingStartDateNotMet",
    type: "error",
  },
  { inputs: [], name: "SukukManager__InsufficientBalance", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "actual", type: "uint256" },
    ],
    name: "SukukManager__InsufficientHoldingAmount",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "actual", type: "uint256" },
    ],
    name: "SukukManager__InsufficientHoldingDuration",
    type: "error",
  },
  { inputs: [], name: "SukukManager__InvalidStatus", type: "error" },
  { inputs: [], name: "SukukManager__NoRedemptionRequest", type: "error" },
  { inputs: [], name: "SukukManager__NoSupportedTokens", type: "error" },
  { inputs: [], name: "SukukManager__NotIssuer", type: "error" },
  { inputs: [], name: "SukukManager__NotMatured", type: "error" },
  { inputs: [], name: "SukukManager__SaleNotActive", type: "error" },
  { inputs: [], name: "SukukManager__SnapshotDoesNotExist", type: "error" },
  {
    inputs: [],
    name: "SukukManager__StatusTransitionNotAllowed",
    type: "error",
  },
  { inputs: [], name: "SukukManager__SukukAlreadyRegistered", type: "error" },
  { inputs: [], name: "SukukManager__SukukNotRegistered", type: "error" },
  { inputs: [], name: "SukukManager__TransferFailed", type: "error" },
  { inputs: [], name: "SukukManager__Unauthorized", type: "error" },
  { inputs: [], name: "SukukManager__UnsupportedToken", type: "error" },
  { inputs: [], name: "SukukManager__ZeroAddress", type: "error" },
  { inputs: [], name: "SukukManager__ZeroAmount", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "holder",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "HolderAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "holder",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newBalance",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "HolderUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
    ],
    name: "RedemptionApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
    ],
    name: "RedemptionRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "active", type: "bool" },
    ],
    name: "SaleStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minDuration",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "startDate",
        type: "uint256",
      },
    ],
    name: "SnapshotCriteriaUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "snapshotId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "holderCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "eligibleCount",
        type: "uint256",
      },
    ],
    name: "SnapshotTaken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "SukukPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: true,
        internalType: "enum SukukToken.SukukStatus",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "SukukStatusUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "distributionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "YieldClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sukuk",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "distributionId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "YieldDistributed",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "address", name: "token", type: "address" },
    ],
    name: "addSupportedToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "allSukukTokens",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "approveRedemption",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "autoUpdateStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "paymentToken", type: "address" },
    ],
    name: "buySukuk",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "canDistributeYield",
    outputs: [{ internalType: "bool", name: "allowed", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "canPurchase",
    outputs: [{ internalType: "bool", name: "allowed", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "canRedeem",
    outputs: [{ internalType: "bool", name: "allowed", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "checkAutoUpdate",
    outputs: [
      { internalType: "bool", name: "needsUpdate", type: "bool" },
      {
        internalType: "enum SukukToken.SukukStatus",
        name: "suggestedStatus",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "address", name: "holder", type: "address" },
    ],
    name: "checkYieldEligibility",
    outputs: [
      { internalType: "bool", name: "eligible", type: "bool" },
      { internalType: "string", name: "reason", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "uint256", name: "distributionId", type: "uint256" },
    ],
    name: "claimYield",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "uint256", name: "minHoldingAmount", type: "uint256" },
      { internalType: "uint256", name: "minHoldingDuration", type: "uint256" },
      { internalType: "uint256", name: "holdingStartDate", type: "uint256" },
    ],
    name: "configureSnapshotCriteria",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "uint256", name: "snapshotId", type: "uint256" },
      { internalType: "uint256", name: "totalYieldAmount", type: "uint256" },
      { internalType: "address", name: "paymentToken", type: "address" },
    ],
    name: "distributeYieldFromSnapshot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "getActiveHolders",
    outputs: [
      { internalType: "address[]", name: "activeHolders", type: "address[]" },
      { internalType: "uint256[]", name: "balances", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "offset", type: "uint256" },
      { internalType: "uint256", name: "limit", type: "uint256" },
    ],
    name: "getAllSukukTokens",
    outputs: [{ internalType: "address[]", name: "tokens", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "getEligibleHolders",
    outputs: [
      { internalType: "address[]", name: "eligibleHolders", type: "address[]" },
      {
        internalType: "uint256[]",
        name: "eligibleBalances",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "address", name: "holder", type: "address" },
    ],
    name: "getHolderInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "firstAcquisitionTime",
            type: "uint256",
          },
          { internalType: "uint256", name: "currentBalance", type: "uint256" },
          { internalType: "uint256", name: "lastUpdateTime", type: "uint256" },
          { internalType: "bool", name: "isActive", type: "bool" },
        ],
        internalType: "struct SukukManager.HolderInfo",
        name: "info",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "getNextSnapshotId",
    outputs: [{ internalType: "uint256", name: "nextId", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "uint256", name: "snapshotId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "getSnapshotBalance",
    outputs: [{ internalType: "uint256", name: "balance", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "getSnapshotCriteria",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "minHoldingAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minHoldingDuration",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "holdingStartDate",
            type: "uint256",
          },
          { internalType: "bool", name: "isConfigured", type: "bool" },
        ],
        internalType: "struct SukukManager.SnapshotCriteria",
        name: "criteria",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "uint256", name: "snapshotId", type: "uint256" },
    ],
    name: "getSnapshotInfo",
    outputs: [
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "uint256", name: "totalSupply", type: "uint256" },
      { internalType: "uint256", name: "holderCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "getSukukHolders",
    outputs: [
      { internalType: "address[]", name: "holders", type: "address[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "getSukukStatus",
    outputs: [
      {
        internalType: "enum SukukToken.SukukStatus",
        name: "status",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "getSukukStatusString",
    outputs: [{ internalType: "string", name: "statusString", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "issuer", type: "address" }],
    name: "getSukukTokensByIssuer",
    outputs: [{ internalType: "address[]", name: "tokens", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum SukukToken.SukukStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "getSukukTokensByStatus",
    outputs: [{ internalType: "address[]", name: "tokens", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "getSupportedTokens",
    outputs: [{ internalType: "address[]", name: "tokens", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalSukukCount",
    outputs: [{ internalType: "uint256", name: "count", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "holderInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "firstAcquisitionTime",
        type: "uint256",
      },
      { internalType: "uint256", name: "currentBalance", type: "uint256" },
      { internalType: "uint256", name: "lastUpdateTime", type: "uint256" },
      { internalType: "bool", name: "isActive", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "isHolder",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "address", name: "token", type: "address" },
    ],
    name: "isSupportedToken",
    outputs: [{ internalType: "bool", name: "supported", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "nextSnapshotId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "redemptionRequests",
    outputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "paymentToken", type: "address" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "address", name: "issuer", type: "address" },
      { internalType: "address[]", name: "supportedTokens", type: "address[]" },
    ],
    name: "registerSukuk",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "registeredSukuk",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "paymentToken", type: "address" },
    ],
    name: "requestRedemption",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      { internalType: "bool", name: "active", type: "bool" },
    ],
    name: "setSaleActive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "snapshotCriteria",
    outputs: [
      { internalType: "uint256", name: "minHoldingAmount", type: "uint256" },
      { internalType: "uint256", name: "minHoldingDuration", type: "uint256" },
      { internalType: "uint256", name: "holdingStartDate", type: "uint256" },
      { internalType: "bool", name: "isConfigured", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "snapshots",
    outputs: [
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "uint256", name: "totalSupply", type: "uint256" },
      { internalType: "bool", name: "exists", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "sukukHolders",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "sukukInfo",
    outputs: [
      { internalType: "address", name: "sukukToken", type: "address" },
      { internalType: "address", name: "issuer", type: "address" },
      { internalType: "bool", name: "saleActive", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "sukuk", type: "address" }],
    name: "takeSnapshot",
    outputs: [{ internalType: "uint256", name: "snapshotId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sukuk", type: "address" },
      {
        internalType: "enum SukukToken.SukukStatus",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "updateSukukStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "yieldVault",
    outputs: [
      { internalType: "contract YieldVault", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
